### ISSUE TITLE
Use iaso mobile app with local server instance.

### ISSUE THREAD

**Issue by enokby** [BLSQ/iaso#1119]
Hello BLSQ team, I would like to run IASO mobile app on local with Bluestack and connect it to a local instance running on localhost:8081. I'm going through and error with no detail:
![image](https://github.com/BLSQ/iaso/assets/5192802/a10d1344-76cb-4994-bef8-e131474711e9)
How could I solve the issue ?

**Comment by madewulf** [comment]
Hi, this means that the mobile app does not find configuration information on the server. 

There are multiple things to check here: 
- Is the address you put for the server accessible to the mobile app? localhost:8081 is not accessible from your phone, for example. You need to expose your local server to internet, or to the network to which your phone is connected. (to check if this is the problem, see if the server logs show access by the mobile application). 
- If the connection is ok, check if there is a project (it's under admin in the menu for your account) on your server with the app_id in the screenshot.

**Comment by enokby** [comment]
I have just disabled the firewall to make sure it is not causing any issue but the adress is accesssible from the phone as you can see here:
![app](https://github.com/BLSQ/iaso/assets/5192802/34d52ac7-1024-4067-8df2-d2ec471f712b)
and the choosen app id is also set:
![image](https://github.com/BLSQ/iaso/assets/5192802/eaa01c26-6383-4729-882d-85fa1f1b7ddd)

**Comment by madewulf** [comment]
OK, just membered that https with a valid certificate is mandatory for the mobile application, for security reasons. 

You can use a service like ngrok to expose your local server to internet, if you are looking for an easy solution.

**Comment by enokby** [comment]
Ok I understand. Thank you very much @madewulf.

**Comment by enokby** [comment]
Ok I understand. Thank you very much @madewulf.
