### ISSUE TITLE
Greetings / FYI about OpenRosa specification

### ISSUE THREAD

**Issue by jnm** [BLSQ/iaso#71]
Hello, 

I saw these [reverse engineering notes](https://github.com/BLSQ/iaso/blob/development/REVERSE-ENKETO.md#reverse-engineer-notes--api-calls-from-enketo) and just wanted to chime in with a link to the official documentation of `formList`, `submission` and friends in case you hadn't seen it already: https://docs.getodk.org/openrosa/.

Good luck with your project!

John Milner
KoBoToolbox

**Comment by madewulf** [comment]
We saw that actually, but this shows that our documentation there is a bit outdated already. Thanks!
